name: Sync with upstream
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add upstream remote
        run: git remote add upstream https://github.com/zrax/pycdc.git
      - name: Fetch upstream changes
        run: git fetch upstream
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Merge upstream changes
        run: git merge upstream/main --no-edit
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
